export const ACTIONS = {
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ALL_CART: "REMOVE_ALL_CART",
  SELECT_ITEMS: "SELECT_ITEMS",
  SET_USER: "SET_USER",          
  CLEAR_USER: "CLEAR_USER",    
    ADD_ORDER: "ADD_ORDER", 
    LOGOUT_USER:"LOGOUT_USER",
    CLEAR_CART:"CLEAR_CART"
    
    

};
