export const ACTIONS = {
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ALL_CART: "REMOVE_ALL_CART",
  SELECT_ITEMS: "SELECT_ITEMS",
};
